name: Limit file size

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: pip install lizard

    - name: Gather size
      run: |
        echo $HOME
        $HOME/.local/bin/lizard > .github/workflows/sizes.txt
        cat .github/workflows/sizes.txt

    - name: Check size
      run: bash .github/workflows/lpar.sh 50 .github/workflows/sizes.txt
